# Generated by Django 2.1.1 on 2018-10-09 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='url',
            new_name='media_url',
        ),
    ]
