# Generated by Django 2.1.1 on 2018-10-03 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_auto_20181003_1724'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='score',
        ),
    ]
