# Generated by Django 2.1.1 on 2018-09-29 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180928_1713'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='orcid_id',
            new_name='orcid',
        ),
    ]
