# Generated by Django 2.1.2 on 2018-10-02 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20181001_1714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermentor',
            name='mentor',
        ),
        migrations.RemoveField(
            model_name='usermentor',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserMentor',
        ),
    ]
